name: AntiCheat
main: me.Jack.anticheat.Anticheat
version: 1.3.4
author: Jack223
description: > 
             Stops Cheaters!

commands:
   ac:
    description: Anticheat Command
   qop:
     description: QOP checks for hacks on a player
